# SPDX-FileCopyrightText: 2022 René de Hesselle <dehesselle@web.de>
#
# SPDX-License-Identifier: MIT

# Use this template to verify an SDK against the checksums.
#
# Requirements:
# - Set SDKROOT to a fully-qualified path of either
#     <fully-qualified path here>/MacOSX10.11.4.sdk
#     <fully-qualified path here>/MacOSX10.13.4.sdk
#     <fully-qualified path here>/MacOSX10.15.6.sdk
#     <fully-qualified path here>/MacOSX11.3.sdk

.verify_sdk:
  script:
    - |
      git clone https://github.com/dehesselle/sdkchecksum
      shasum -a 256 sdkchecksum/$(basename $SDKROOT).sha256
      cd $(dirname $SDKROOT)
      if shasum -s -c $CI_PROJECT_DIR/sdkchecksum/$(basename $SDKROOT).sha256; then
        echo "ok - SDK verified"
        exit 0
      else
        echo "error - SDK verification failed"
        exit 1
      fi
